//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS_Sunstate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMS_Sunstate.Resources.GetData", typeof(GetData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch top=&apos;5&apos; version=&apos;1.0&apos; output-format=&apos;xml-platform&apos; mapping=&apos;logical&apos; distinct=&apos;false&apos; &gt;
        ///                      &lt;entity name=&apos;sse_bidder&apos;&gt;
        ///                        &lt;attribute name=&apos;sse_name&apos; /&gt;
        ///                        &lt;attribute name=&apos;createdon&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_bidderid&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_factorkey&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_dodge_companyname&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_dodge_streetaddress&apos; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllActiveRecords {
            get {
                return ResourceManager.GetString("GetAllActiveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&apos;1.0&apos; output-format=&apos;xml-platform&apos; mapping=&apos;logical&apos; distinct=&apos;false&apos;&gt;
        ///                  &lt;entity name=&apos;sse_bidder&apos;&gt;
        ///                        &lt;attribute name=&apos;sse_name&apos; /&gt;
        ///                        &lt;attribute name=&apos;createdon&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_bidderid&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_factorkey&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_dodge_companyname&apos; /&gt;
        ///                        &lt;attribute name=&apos;sse_dodge_streetaddress&apos; /&gt;
        ///	         &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDuplicateRecords {
            get {
                return ResourceManager.GetString("GetDuplicateRecords", resourceCulture);
            }
        }
    }
}
